### ISSUE TITLE
Affinity property doesn't work

### ISSUE THREAD

**Issue by diegopereiraeng** [Appdynamics/appdynamics-operator#73]
Hi,

I have an machine agent running as daemonset outside operator with this affinity:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: In
            values:
            - "true"
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: In
            values:
            - "true"
        - matchExpressions:
          - key: node-role.kubernetes.io/compute
            operator: In
            values:
            - "true"
            - "false"

How do Implement this in infraviz-opensshift.yaml?

**Comment by ankur8** [comment]
Yes affinity and toleration are not working on k8s version 1.20.5 i checked

**Comment by ankur8** [comment]
@diegopereiraeng  which version of cluster agent you tested

**Comment by diegopereiraeng** [comment]
The customer has 1.13 version

**Comment by arunkath123** [comment]
@ankur8 @diegopereiraeng  -- Node affinity is a feature of the cluster... How can this be a problem with agent?

**Comment by arunkath123** [comment]
@diegopereiraeng where did you place your Nodeaffinity parameters?
They should ideally go into   the cluster-agent-operator.yaml into the appdynamics-operator deployment section.

**Comment by ankur8** [comment]
it is resolved now at my end @arunkath123  and @diegopereiraeng

**Comment by arunkath123** [comment]
Well done @ankur8 ! Can you brief on what was done?

**Comment by diegopereiraeng** [comment]
I still don't know how to set node affinity in infraviz infraviz-openshift.yaml since it is not a deployment and it is a kind: InfraViz
